image:
  - Visual Studio 2017
  - Visual Studio 2015

platform:
  - x64

build:
  #project: code/cpp/std_normal_distribution
  verbosity: minimal
  parallel: true

matrix:
  fast_finish: false

configuration:
  - Debug
  - Release

build_script:
  - sh: pwd
  - cmake --version
  - cmake -H. -Bbuild -A%PLATFORM% ..
  - cmake --build build --config %CONFIGURATION%

test_script:
  - sh: pwd
  - mkdir build
  - cd build
  - cmake -H. -Bbuild -A%PLATFORM% ..
  - cmake --build build --config %CONFIGURATION%
  - ctest
