image:
  - Visual Studio 2017
  - Visual Studio 2015

platform:
  - x64

build: off
  
matrix:
  fast_finish: false

configuration:
  - Debug
  - Release

build_script:
  - cmake --version
  - cmake -H. -Bbuild -A%PLATFORM% ..
  - cmake --build build --config %CONFIGURATION%

test_script:
  - cmake -H. -Bbuild -A%PLATFORM% ..
  - cmake --build build --config %CONFIGURATION%
  - ctest
